import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F9F9F9'},
  center: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  statsBar: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  statItem: {flex: 1, alignItems: 'center'},
  statValue: {fontSize: 20, fontWeight: '700', color: '#007AFF'},
  statValueGreen: {fontSize: 20, fontWeight: '700', color: '#34C759'},
  statValueRed: {fontSize: 20, fontWeight: '700', color: '#FF3B30'},
  statValueOrange: {fontSize: 20, fontWeight: '700', color: '#FF9500'},
  statLabel: {fontSize: 11, color: '#888', marginTop: 2},
  codeBanner: {
    backgroundColor: '#007AFF',
    marginHorizontal: 12,
    marginTop: 12,
    padding: 20,
    alignItems: 'center',
    borderRadius: 14,
  },
  codeBannerLabel: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.85)',
    marginBottom: 8,
    textAlign: 'center',
  },
  codeText: {fontSize: 42, fontWeight: '900', color: '#fff', letterSpacing: 8},
  codeExpiry: {fontSize: 12, color: 'rgba(255,255,255,0.75)', marginTop: 6},
  codeAction: {
    marginTop: 12,
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
  },
  codeActionText: {color: '#fff', fontWeight: '700', fontSize: 13},
  disputeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    margin: 12,
    borderRadius: 10,
  },
  disputeBannerText: {fontSize: 13, color: '#333', flex: 1},
  list: {padding: 16, paddingBottom: 40},
  empty: {textAlign: 'center', color: '#999', marginTop: 40},
  historyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  historyBannerText: {fontSize: 13, fontWeight: '600', color: '#555'},
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  cardTop: {flexDirection: 'row', alignItems: 'center', gap: 12},
  cardInfo: {flex: 1},
  cardDay: {fontSize: 14, fontWeight: '600', color: '#1a1a1a'},
  cardTime: {fontSize: 13, fontWeight: '500', color: '#444', marginTop: 2},
  cardDate: {fontSize: 12, color: '#888', marginTop: 2},
  noteBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 6,
    backgroundColor: '#FFF3EE',
    borderRadius: 6,
    padding: 6,
  },
  noteText: {fontSize: 12, color: '#FF6B35', flex: 1, lineHeight: 16},
  planBox: {
    marginTop: 12,
    backgroundColor: '#F3F8FF',
    borderRadius: 10,
    padding: 12,
  },
  planHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  planTitle: {fontSize: 13, fontWeight: '700', color: '#007AFF'},
  planItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 10,
  },
  planItemContent: {flex: 1},
  planItemName: {fontSize: 13, fontWeight: '600', color: '#1a1a1a'},
  planItemDetail: {fontSize: 12, color: '#667085', marginTop: 2},
  confirmBtn: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  confirmBtnDisabled: {opacity: 0.5},
  confirmBtnText: {color: '#fff', fontWeight: '700', fontSize: 13},
  codeRow: {flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10},
  codeInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: 10,
    fontSize: 20,
    textAlign: 'center',
    letterSpacing: 6,
    color: '#333',
  },
  disputeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#FF3B30',
    borderRadius: 10,
  },
  disputeBtnText: {color: '#FF3B30', fontWeight: '600', fontSize: 14},
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalBox: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: {fontSize: 18, fontWeight: '700', color: '#333', marginBottom: 6},
  modalSubtitle: {fontSize: 13, color: '#888', marginBottom: 16},
  reasonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    marginBottom: 6,
    backgroundColor: '#F9F9F9',
  },
  reasonRowActive: {backgroundColor: '#E3F2FD'},
  reasonText: {fontSize: 14, color: '#333'},
  reasonTextActive: {fontSize: 14, color: '#007AFF'},
  descInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#333',
    marginTop: 12,
    marginBottom: 16,
    minHeight: 80,
  },
  modalBtns: {flexDirection: 'row', gap: 10},
  cancelBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#F0F0F0',
  },
  cancelText: {color: '#666', fontWeight: '600'},
  submitBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#FF3B30',
  },
  submitBtnDisabled: {opacity: 0.6},
  submitText: {color: '#fff', fontWeight: '700'},
});
