import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F9F9F9'},
  filterSection: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EFEFEF',
    gap: 10,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F6F6F6',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    paddingHorizontal: 12,
    minHeight: 44,
  },
  searchInput: {flex: 1, fontSize: 14, color: '#333', paddingVertical: 10},
  filterTabs: {gap: 8, paddingRight: 16},
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#F2F2F2',
  },
  filterChipActive: {backgroundColor: '#FF6B35'},
  filterChipText: {fontSize: 12, fontWeight: '600', color: '#666'},
  filterChipTextActive: {color: '#fff'},
  center: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  empty: {alignItems: 'center', paddingTop: 80},
  emptyText: {fontSize: 16, color: '#999', marginTop: 12, fontWeight: '600'},
  emptySubText: {
    fontSize: 13,
    color: '#bbb',
    marginTop: 6,
    textAlign: 'center',
    paddingHorizontal: 40,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  cardHeader: {marginBottom: 8},
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
    flex: 1,
    marginRight: 8,
  },
  activeBadge: {paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8},
  activeBadgeText: {fontSize: 11, fontWeight: '700'},
  adminNoteBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#FFF7E6',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  adminNoteText: {
    flex: 1,
    fontSize: 12,
    color: '#8A6200',
    lineHeight: 18,
    fontWeight: '600',
  },
  cardPrice: {fontSize: 15, fontWeight: '600', color: '#FF6B35'},
  cardDesc: {fontSize: 13, color: '#666', marginBottom: 8, lineHeight: 18},
  metaRow: {flexDirection: 'row', alignItems: 'center', marginBottom: 4},
  metaText: {fontSize: 13, color: '#666'},
  clientLockRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 8,
  },
  clientLockText: {
    flex: 1,
    fontSize: 12,
    color: '#C47A00',
    lineHeight: 18,
    fontWeight: '600',
  },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    paddingTop: 12,
  },
  toggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F5F5F5',
  },
  viewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F3F4F6',
  },
  viewText: {fontSize: 13, color: '#333', fontWeight: '600'},
  toggleText: {fontSize: 13, color: '#666'},
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#E3F2FD',
  },
  editText: {fontSize: 13, color: '#007AFF', fontWeight: '600'},
  deleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#FFF0F0',
  },
  deleteText: {fontSize: 13, color: '#FF3B30', fontWeight: '600'},
  actionDisabled: {opacity: 0.45},
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FF6B35',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#FF6B35',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  modalContainer: {flex: 1, backgroundColor: '#fff'},
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalTitle: {fontSize: 18, fontWeight: 'bold', color: '#333'},
  modalBody: {padding: 20},
  detailLoadingWrap: {
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailHero: {
    backgroundColor: '#FFF7F3',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#FFE1D6',
  },
  detailTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  detailTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '700',
    color: '#222',
  },
  detailPrice: {
    marginTop: 10,
    fontSize: 17,
    fontWeight: '700',
    color: '#FF6B35',
  },
  detailRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
  },
  detailRatingText: {fontSize: 14, fontWeight: '700', color: '#333'},
  detailRatingCount: {fontSize: 13, color: '#777'},
  detailSubtleText: {marginTop: 10, fontSize: 13, color: '#888'},
  detailSection: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  detailSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    marginBottom: 12,
  },
  detailBodyText: {fontSize: 14, lineHeight: 21, color: '#555'},
  detailInfoRow: {marginBottom: 10},
  detailInfoLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#888',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  detailInfoValue: {fontSize: 14, color: '#444', lineHeight: 20},
  detailScheduleBlock: {marginTop: 2},
  detailScheduleText: {fontSize: 14, color: '#444', lineHeight: 22},
  reviewCard: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  reviewAuthor: {fontSize: 14, fontWeight: '700', color: '#333'},
  reviewStars: {flexDirection: 'row', gap: 1},
  reviewDate: {fontSize: 11, color: '#B0B0B0', marginLeft: 'auto'},
  reviewText: {fontSize: 14, color: '#555', lineHeight: 20},
  emptyReviewsText: {fontSize: 14, color: '#888'},
  fieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
    marginTop: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    color: '#333',
    backgroundColor: '#F9F9F9',
    marginBottom: 16,
  },
  textArea: {minHeight: 90},
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  saveBtn: {
    backgroundColor: '#FF6B35',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  saveBtnText: {color: '#fff', fontSize: 16, fontWeight: 'bold'},
  toggleRow: {flexDirection: 'row', gap: 10, marginBottom: 16},
  toggleOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#F0F0F0',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  toggleOptionActive: {backgroundColor: '#FF6B35', borderColor: '#FF6B35'},
  toggleOptionText: {fontSize: 14, fontWeight: '600', color: '#666'},
  toggleOptionTextActive: {color: '#fff'},
  addSlotBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#FFF0EB',
  },
  addSlotText: {fontSize: 13, color: '#FF6B35', fontWeight: '600'},
  hintText: {
    fontSize: 12,
    color: '#aaa',
    fontStyle: 'italic',
    marginBottom: 12,
  },
  scheduleRow: {
    backgroundColor: '#F9F9F9',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  dayPicker: {marginBottom: 8},
  dayChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#F0F0F0',
    marginRight: 6,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  dayChipActive: {backgroundColor: '#FF6B35', borderColor: '#FF6B35'},
  dayChipText: {fontSize: 13, color: '#666', fontWeight: '500'},
  dayChipTextActive: {color: '#fff', fontWeight: '700'},
  timeRow: {flexDirection: 'row', alignItems: 'center', gap: 6},
  timeInput: {flex: 1, marginBottom: 0, textAlign: 'center'},
  timeSep: {fontSize: 14, color: '#666', fontWeight: '600'},
});
