import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#f5f5f5'},
  scrollView: {flex: 1},
  header: {padding: 16, backgroundColor: '#fff'},
  backButton: {width: 40, height: 40, justifyContent: 'center'},
  profileSection: {
    backgroundColor: '#fff',
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  profileImage: {width: 120, height: 120, borderRadius: 60, marginBottom: 16},
  profileImagePlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  profileImagePlaceholderText: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#fff',
  },
  trainerName: {fontSize: 28, fontWeight: 'bold', marginBottom: 8},
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  rating: {fontSize: 18, fontWeight: '600', marginLeft: 6},
  ratingCount: {fontSize: 14, color: '#666', marginLeft: 4},
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  contactText: {fontSize: 14, color: '#555', fontWeight: '500'},
  profileFactsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
  },
  profileFactChip: {
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  profileFactText: {fontSize: 12, color: '#555', fontWeight: '600'},
  trainerBio: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 20,
    paddingHorizontal: 8,
  },
  trainerSpecRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  trainerSpecText: {fontSize: 13, color: '#007AFF', fontWeight: '500'},
  infoChipsSection: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 12,
    borderRadius: 0,
  },
  infoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  infoChipText: {fontSize: 13, fontWeight: '600'},
  locationRow: {flexDirection: 'row', alignItems: 'flex-start', gap: 8},
  locationText: {
    fontSize: 15,
    color: '#007AFF',
    flex: 1,
    lineHeight: 22,
    textDecorationLine: 'underline',
    fontWeight: '500',
  },
  scheduleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  scheduleDayBadge: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
    minWidth: 90,
    alignItems: 'center',
  },
  scheduleDayText: {color: '#fff', fontSize: 13, fontWeight: '700'},
  scheduleTimeRow: {flexDirection: 'row', alignItems: 'center', gap: 6},
  scheduleTimeText: {fontSize: 14, color: '#555', fontWeight: '500'},
  section: {backgroundColor: '#fff', padding: 20, marginTop: 12},
  sectionTitle: {fontSize: 20, fontWeight: '600', marginBottom: 16},
  description: {fontSize: 16, color: '#666', lineHeight: 24},
  specializationContainer: {gap: 12},
  specializationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 8,
  },
  specializationText: {fontSize: 16, color: '#007AFF', fontWeight: '500'},
  certificationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  certificationText: {fontSize: 16, color: '#333'},
  benefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  benefitText: {fontSize: 16, color: '#333'},
  bottomPadding: {height: 100},
  footer: {
    backgroundColor: '#fff',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  priceSection: {marginBottom: 12},
  priceLabel: {fontSize: 14, color: '#666', marginBottom: 4},
  price: {fontSize: 24, fontWeight: 'bold', color: '#34C759'},
  statusHint: {
    fontSize: 13,
    color: '#007AFF',
    textAlign: 'center',
    marginTop: 8,
    fontWeight: '500',
  },
  hireButton: {
    backgroundColor: '#007AFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    gap: 8,
  },
  hireButtonText: {color: '#fff', fontSize: 18, fontWeight: '600'},
  buttonDisabled: {opacity: 0.6},
});
