import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#f5f5f5'},
  center: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  tabsRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: '#fff',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#F2F2F2',
  },
  tabButtonActive: {backgroundColor: '#FF6B35'},
  tabButtonText: {fontSize: 13, fontWeight: '700', color: '#666'},
  tabButtonTextActive: {color: '#fff'},
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingBottom: 10,
    backgroundColor: '#fff',
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F2F2F2',
  },
  filterChipActive: {backgroundColor: '#FFE2D6'},
  filterChipText: {fontSize: 12, fontWeight: '600', color: '#666'},
  filterChipTextActive: {color: '#FF6B35'},
  list: {flex: 1},
  listContent: {paddingBottom: 24},
  emptyContent: {flexGrow: 1, justifyContent: 'center'},
  item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    marginHorizontal: 12,
    marginTop: 10,
    backgroundColor: '#fff',
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  info: {flex: 1, marginRight: 10},
  title: {fontSize: 16, fontWeight: '700', color: '#1a1a1a', marginBottom: 5},
  metaRow: {flexDirection: 'row', alignItems: 'center', marginTop: 2},
  duration: {fontSize: 12, color: '#888'},
  points: {fontSize: 12, color: '#FF9500', fontWeight: '600'},
  spotWarningText: {color: '#FF3B30', fontWeight: '600'},
  spotSafeText: {color: '#34C759', fontWeight: '600'},
  rightCol: {alignItems: 'flex-end', gap: 6},
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: '#FFF0EB',
    borderWidth: 1,
    borderColor: '#FF6B35',
  },
  badgeText: {fontSize: 11, fontWeight: '700', color: '#FF6B35'},
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    minWidth: 74,
    alignItems: 'center',
  },
  statusBadgeText: {fontSize: 11, fontWeight: '700'},
  joinedStatusBadge: {backgroundColor: '#E8F7ED'},
  joinedStatusText: {color: '#34C759'},
  pendingBadge: {backgroundColor: '#FFF4D6'},
  pendingBadgeText: {color: '#C47A00'},
  completedBadge: {backgroundColor: '#E7F0FF'},
  completedBadgeText: {color: '#007AFF'},
  endedBadge: {backgroundColor: '#F3F4F6'},
  endedBadgeText: {color: '#6B7280'},
  empty: {textAlign: 'center', marginTop: 60, color: '#999', fontSize: 15},
});
