import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#f5f5f5'},
  center: {flex: 1, justifyContent: 'center', alignItems: 'center'},

  tabBar: {flexDirection: 'row', backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#eee'},
  tab: {flex: 1, paddingVertical: 14, alignItems: 'center'},
  tabActive: {borderBottomWidth: 2, borderBottomColor: '#FF6B35'},
  tabText: {fontSize: 14, fontWeight: '600', color: '#999'},
  tabTextActive: {color: '#FF6B35'},

  actionBar: {
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 8,
  },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FF6B35',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  createButtonText: {fontSize: 15, fontWeight: '700', color: '#fff'},

  filterSection: {backgroundColor: '#fff', paddingHorizontal: 12, paddingTop: 12, paddingBottom: 6, borderBottomWidth: 1, borderBottomColor: '#eee'},
  filterHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 30, marginBottom: 10},
  filterTitle: {fontSize: 16, fontWeight: '700', color: '#333'},
  clearFilterButton: {height: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10, borderRadius: 14, backgroundColor: '#FFF3EC'},
  clearFilterText: {fontSize: 13, fontWeight: '600', color: '#FF6B35'},
  filterLabel: {fontSize: 12, fontWeight: '600', color: '#888', marginBottom: 4, textTransform: 'uppercase', letterSpacing: 0.5},
  filterRow: {height: 44, marginBottom: 8},
  filterContent: {gap: 8, alignItems: 'center'},
  dateRangeRow: {flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12},
  dateRangeField: {flex: 1, minHeight: 48, borderWidth: 1, borderColor: '#E0E0E0', borderRadius: 10, backgroundColor: '#F9F9F9', paddingHorizontal: 12, paddingVertical: 8, justifyContent: 'center'},
  dateRangeFieldValue: {fontSize: 14, color: '#333', fontWeight: '500'},
  dateRangeFieldPlaceholder: {fontSize: 14, color: '#aaa'},
  dateRangeSeparator: {fontSize: 13, color: '#888', fontWeight: '600'},
  filterChip: {height: 34, paddingHorizontal: 14, borderRadius: 17, backgroundColor: '#F0F0F0', borderWidth: 1, borderColor: '#ddd', justifyContent: 'center', alignItems: 'center'},
  filterChipActive: {backgroundColor: '#FF6B35', borderColor: '#FF6B35'},
  filterChipText: {fontSize: 13, color: '#666', fontWeight: '500'},
  filterChipTextActive: {color: '#fff', fontWeight: '600'},

  emptyContainer: {alignItems: 'center', paddingTop: 80},
  emptyText: {fontSize: 15, color: '#999', marginTop: 12},

  item: {
    backgroundColor: '#fff', marginHorizontal: 12, marginTop: 10, borderRadius: 12, padding: 15,
    elevation: 2, shadowColor: '#000', shadowOffset: {width: 0, height: 1}, shadowOpacity: 0.08, shadowRadius: 4,
  },
  info: {marginBottom: 10},
  titleRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6},
  challengeTitle: {fontSize: 15, fontWeight: '700', color: '#1a1a1a', flex: 1, marginRight: 8},
  dateBadge: {paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8},
  dateBadgeActive: {backgroundColor: '#E8F5E9'},
  dateBadgeEnded: {backgroundColor: '#F5F5F5'},
  dateBadgeText: {fontSize: 11, fontWeight: '700'},
  metaRow: {flexDirection: 'row', alignItems: 'center', marginTop: 3},
  metaText: {fontSize: 13, color: '#666'},
  memberName: {fontSize: 14, color: '#555'},
  dateText: {fontSize: 12, color: '#aaa', marginTop: 4},

  actions: {flexDirection: 'row', gap: 10},
  approveButton: {
    flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center',
    backgroundColor: '#34C759', padding: 10, borderRadius: 8,
  },
  rejectButton: {
    flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center',
    backgroundColor: '#FF3B30', padding: 10, borderRadius: 8,
  },
  buttonText: {color: '#fff', fontWeight: '600', fontSize: 14},

  noteBox: {flexDirection: 'row', alignItems: 'flex-start', marginTop: 6, backgroundColor: '#FFF0F0', padding: 8, borderRadius: 8},
  noteText: {fontSize: 12, color: '#FF3B30', flex: 1},
  descText: {fontSize: 13, color: '#666', marginTop: 6, fontStyle: 'italic'},
  detailSection: {fontSize: 12, fontWeight: '700', color: '#FF6B35', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6},
  detailTitle: {fontSize: 16, fontWeight: '700', color: '#333', marginBottom: 6},

  modalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end'},
  modalContent: {backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20},
  modalHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16},
  modalTitle: {fontSize: 18, fontWeight: 'bold', color: '#333'},
  modalLabel: {fontSize: 14, color: '#666', marginBottom: 8},
  textArea: {borderWidth: 1, borderColor: '#E0E0E0', borderRadius: 10, padding: 12, fontSize: 14, color: '#333', minHeight: 100, marginBottom: 16},
  modalActions: {flexDirection: 'row', gap: 10},
  cancelButton: {flex: 1, padding: 14, borderRadius: 10, alignItems: 'center', backgroundColor: '#F0F0F0'},
  cancelButtonText: {color: '#666', fontWeight: '600', fontSize: 15},

  datePickerOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center'},
  datePickerModal: {backgroundColor: '#fff', borderRadius: 20, padding: 20, width: '88%', maxHeight: '70%'},
  datePickerTitle: {fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 16, textAlign: 'center'},
  datePickerColumns: {flexDirection: 'row', gap: 10, marginBottom: 20},
  datePickerColumn: {flex: 1},
  datePickerColumnLabel: {fontSize: 13, fontWeight: '600', color: '#FF6B35', textAlign: 'center', marginBottom: 8},
  datePickerList: {height: 200, borderWidth: 1, borderColor: '#E0E0E0', borderRadius: 10},
  datePickerItem: {padding: 12, alignItems: 'center'},
  datePickerItemActive: {backgroundColor: '#FF6B35'},
  datePickerItemText: {fontSize: 15, color: '#333'},
  datePickerItemTextActive: {color: '#fff', fontWeight: 'bold'},
  datePickerActions: {flexDirection: 'row', gap: 10},
  datePickerCancelButton: {flex: 1, padding: 14, borderRadius: 12, alignItems: 'center', backgroundColor: '#F0F0F0'},
  datePickerConfirmButton: {flex: 1, padding: 14, borderRadius: 12, alignItems: 'center', backgroundColor: '#FF6B35'},
  datePickerCancelButtonText: {color: '#666', fontSize: 15, fontWeight: '600'},
  datePickerConfirmButtonText: {color: '#fff', fontSize: 15, fontWeight: 'bold'},
});
