import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F9F9F9'},
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
  },
  emptyTitle: {fontSize: 18, color: '#333', marginTop: 15, fontWeight: '600'},
  emptySubtitle: {color: '#999', marginTop: 8, textAlign: 'center'},
  emptyButton: {
    marginTop: 20,
    backgroundColor: '#FF6B35',
    padding: 14,
    borderRadius: 12,
  },
  emptyButtonText: {color: '#fff', fontWeight: '600'},
  statusBanner: {padding: 20, margin: 15, borderRadius: 16},
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  statusTitle: {fontSize: 16, fontWeight: 'bold'},
  statusMessage: {fontSize: 13, color: '#666'},
  adminNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.08)',
  },
  adminNoteText: {fontSize: 13, flex: 1, fontStyle: 'italic'},
  planHeader: {backgroundColor: '#fff', padding: 20, marginBottom: 10},
  aiTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#FFF0EB',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 12,
  },
  aiTagText: {fontSize: 12, fontWeight: '600', color: '#FF6B35'},
  planName: {fontSize: 22, fontWeight: 'bold', color: '#333', marginBottom: 4},
  generatedAt: {fontSize: 13, color: '#999'},
  planDaysBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#FFF5EF',
  },
  planDaysText: {flex: 1, fontSize: 12, color: '#C55A11', lineHeight: 18},
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    backgroundColor: '#FF6B35',
    padding: 14,
    borderRadius: 12,
  },
  primaryButtonText: {fontSize: 14, fontWeight: '700', color: '#fff'},
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    borderWidth: 1.5,
    borderColor: '#FF6B35',
    padding: 14,
    borderRadius: 12,
  },
  secondaryButtonDisabled: {opacity: 0.6},
  secondaryButtonText: {fontSize: 14, fontWeight: '700', color: '#FF6B35'},
  regenerateHint: {fontSize: 12, color: '#888', marginTop: 8, lineHeight: 18},
  queueBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFF7E6',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    marginTop: 12,
  },
  queueBannerText: {fontSize: 12, color: '#B26A00', fontWeight: '600'},
  section: {backgroundColor: '#fff', padding: 20, marginBottom: 10},
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  dayCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginBottom: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  dayCardHeader: {backgroundColor: '#FF6B35', padding: 15},
  dayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  dayBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayBadgeText: {fontSize: 15, fontWeight: 'bold', color: '#fff'},
  dayName: {fontSize: 17, fontWeight: '700', color: '#fff', flex: 1},
  dayCaloriesBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  dayCaloriesText: {fontSize: 12, fontWeight: '700', color: '#fff'},
  dayMacros: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  dayMacroItem: {alignItems: 'center', flex: 1},
  dayMacroValue: {fontSize: 15, fontWeight: '700', color: '#fff'},
  dayMacroLabel: {fontSize: 11, color: 'rgba(255,255,255,0.75)', marginTop: 2},
  dayMacroDivider: {
    width: 1,
    height: 28,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  dayBody: {padding: 15},
  recipeRow: {paddingVertical: 12},
  recipeRowBorder: {borderBottomWidth: 1, borderBottomColor: '#eee'},
  mealTypeTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 7,
  },
  mealTypeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF6B35',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  recipeContent: {flexDirection: 'row', alignItems: 'center', gap: 12},
  recipeImage: {width: 68, height: 68, borderRadius: 12},
  recipeImagePlaceholder: {
    width: 68,
    height: 68,
    borderRadius: 12,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  recipeInfo: {flex: 1, gap: 5},
  recipeName: {fontSize: 14, fontWeight: '600', color: '#333', lineHeight: 19},
  recipeMacrosRow: {flexDirection: 'row', alignItems: 'center', gap: 8},
  caloriesBadge: {
    backgroundColor: '#FF6B35',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  caloriesBadgeText: {fontSize: 11, fontWeight: 'bold', color: '#fff'},
  prepTime: {fontSize: 12, color: '#888'},
  macroTagsRow: {flexDirection: 'row', gap: 5},
  macroTag: {
    fontSize: 11,
    color: '#666',
    backgroundColor: '#eee',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    gap: 14,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {fontSize: 18, fontWeight: '700', color: '#333'},
  modalDescription: {fontSize: 13, color: '#666', lineHeight: 20},
  modalSectionTitle: {fontSize: 13, fontWeight: '700', color: '#333'},
  reasonChips: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  reasonChip: {
    backgroundColor: '#F3F4F6',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  reasonChipActive: {backgroundColor: '#FF6B35'},
  reasonChipText: {fontSize: 12, fontWeight: '600', color: '#555'},
  reasonChipTextActive: {color: '#fff'},
  feedbackInput: {
    minHeight: 96,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#333',
    backgroundColor: '#FAFAFA',
  },
  modalActions: {flexDirection: 'row', gap: 10},
  modalCancelButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
  },
  modalCancelButtonText: {fontSize: 14, fontWeight: '600', color: '#666'},
  modalSubmitButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#FF6B35',
  },
  modalSubmitButtonText: {fontSize: 14, fontWeight: '700', color: '#fff'},
});
