import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#f5f5f5'},
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  loadingText: {marginTop: 12, fontSize: 16, color: '#666'},
  header: {
    backgroundColor: '#fff',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  title: {fontSize: 28, fontWeight: 'bold', marginBottom: 4},
  subtitle: {fontSize: 14, color: '#666'},
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 14,
  },
  searchInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    paddingHorizontal: 12,
    minHeight: 46,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#111',
    paddingVertical: 10,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EAF3FF',
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 46,
    gap: 6,
  },
  filterButtonText: {fontSize: 13, fontWeight: '700', color: '#007AFF'},
  filterCountBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  filterCountText: {fontSize: 11, fontWeight: '700', color: '#fff'},
  activeFilterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    gap: 10,
  },
  activeFilterScroll: {gap: 8, paddingRight: 8},
  activeFilterChip: {
    backgroundColor: '#EFF6FF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  activeFilterChipText: {fontSize: 12, fontWeight: '600', color: '#2563EB'},
  clearFiltersText: {fontSize: 13, fontWeight: '700', color: '#FF6B35'},
  listContainer: {padding: 16},
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardHeader: {flexDirection: 'row', marginBottom: 12},
  profileImage: {width: 60, height: 60, borderRadius: 30, marginRight: 12},
  profileImagePlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#007AFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  profileImagePlaceholderText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  headerInfo: {flex: 1, minWidth: 0, justifyContent: 'center'},
  trainerName: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 4,
    color: '#111',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  rating: {fontSize: 14, fontWeight: '600', marginLeft: 4, color: '#000'},
  experience: {fontSize: 14, color: '#666', marginLeft: 4},
  phoneRow: {flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 6},
  phoneText: {fontSize: 13, color: '#666'},
  profileFactsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  profileFactChip: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
  },
  profileFactText: {fontSize: 11, color: '#555', fontWeight: '600'},
  description: {fontSize: 14, color: '#666', lineHeight: 20, marginBottom: 12},
  specializationContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 12,
    gap: 8,
  },
  specializationBadge: {
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  specializationText: {fontSize: 12, color: '#007AFF', fontWeight: '500'},
  cardFooter: {
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  cardMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  metaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
  },
  metaBadgeWarning: {backgroundColor: '#FFF3E0'},
  metaBadgeInfo: {backgroundColor: '#EAF3FF'},
  metaBadgeNeutral: {backgroundColor: '#F3F4F6'},
  metaBadgeText: {fontSize: 11, fontWeight: '600'},
  metaBadgeWarningText: {color: '#FF9500'},
  metaBadgeInfoText: {color: '#007AFF'},
  metaBadgeNeutralText: {color: '#555'},
  cardActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  priceContainer: {flex: 1, minWidth: 0},
  priceLabel: {fontSize: 12, color: '#666', marginBottom: 2},
  price: {fontSize: 18, fontWeight: 'bold', color: '#34C759'},
  payButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#007AFF',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
    flexShrink: 0,
  },
  payButtonText: {fontSize: 14, fontWeight: '600', color: '#fff'},
  mySubsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  mySubsText: {fontSize: 14, color: '#007AFF', fontWeight: '500'},
  emptyState: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 48,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    marginTop: 12,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 13,
    color: '#888',
    marginTop: 6,
    textAlign: 'center',
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
    maxHeight: '82%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  modalTitle: {fontSize: 20, fontWeight: '700', color: '#111'},
  modalContent: {paddingBottom: 12},
  filterSection: {marginBottom: 18},
  filterLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333',
    marginBottom: 10,
  },
  optionRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  optionChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#F3F4F6',
  },
  optionChipActive: {backgroundColor: '#007AFF'},
  optionChipText: {fontSize: 13, fontWeight: '600', color: '#555'},
  optionChipTextActive: {color: '#fff'},
  priceRow: {flexDirection: 'row', gap: 10},
  filterInput: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#111',
  },
  filterInputFull: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#111',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  resetButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    paddingVertical: 14,
    alignItems: 'center',
  },
  resetButtonText: {fontSize: 14, fontWeight: '700', color: '#555'},
  applyButton: {
    flex: 1.2,
    borderRadius: 12,
    backgroundColor: '#007AFF',
    paddingVertical: 14,
    alignItems: 'center',
  },
  applyButtonText: {fontSize: 14, fontWeight: '700', color: '#fff'},
});
