import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F5F5F5'},
  tabs: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    gap: 8,
  },
  tab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F0F0F0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tabActive: {backgroundColor: '#FF6B35'},
  tabText: {fontSize: 13, fontWeight: '600', color: '#666'},
  tabTextActive: {color: '#fff'},
  badge: {
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 1,
  },
  badgeText: {fontSize: 11, fontWeight: '700', color: '#FF6B35'},
  toolsSection: {
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F6F6F6',
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderRadius: 12,
    paddingHorizontal: 12,
    minHeight: 44,
  },
  searchInput: {flex: 1, fontSize: 14, color: '#333', paddingVertical: 10},
  filterGroup: {gap: 8},
  filterGroupLabel: {fontSize: 12, fontWeight: '700', color: '#888'},
  roleFilters: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#F0F0F0',
  },
  filterChipActive: {backgroundColor: '#FF6B35'},
  filterChipText: {fontSize: 12, fontWeight: '600', color: '#666'},
  filterChipTextActive: {color: '#fff'},
  loader: {flex: 1},
  list: {padding: 12, gap: 10},
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.06,
    shadowRadius: 2,
  },
  cardLeft: {flexDirection: 'row', alignItems: 'center', gap: 12},
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarImg: {width: 46, height: 46, borderRadius: 23},
  avatarText: {fontSize: 18, fontWeight: '700'},
  trainerAvatar: {backgroundColor: '#FF950022'},
  trainerAvatarText: {color: '#FF9500'},
  info: {flex: 1},
  name: {fontSize: 15, fontWeight: '600', color: '#333'},
  email: {fontSize: 13, color: '#888', marginTop: 2},
  meta: {fontSize: 12, color: '#666', marginTop: 2},
  badgeRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4},
  roleBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  roleText: {fontSize: 11, fontWeight: '600', textTransform: 'capitalize'},
  statusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  statusBadgeActive: {backgroundColor: '#E8F5E9'},
  statusBadgeBanned: {backgroundColor: '#FDECEC'},
  statusBadgeText: {fontSize: 11, fontWeight: '600'},
  statusBadgeTextActive: {color: '#2E7D32'},
  statusBadgeTextBanned: {color: '#C62828'},
  detail: {marginTop: 12},
  divider: {height: 1, backgroundColor: '#F0F0F0', marginBottom: 12},
  infoGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12},
  infoItem: {
    backgroundColor: '#F9F9F9',
    borderRadius: 8,
    padding: 10,
    minWidth: '47%',
    flex: 1,
  },
  infoLabel: {fontSize: 11, color: '#999', marginTop: 4, marginBottom: 2},
  infoValue: {fontSize: 13, fontWeight: '600', color: '#333'},
  bioBox: {
    backgroundColor: '#F9F9F9',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  bioLabel: {
    fontSize: 11,
    color: '#999',
    marginBottom: 4,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  bioText: {fontSize: 14, color: '#444', lineHeight: 20},
  certTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#333',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  certImage: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    backgroundColor: '#F0F0F0',
    marginBottom: 4,
  },
  certImageHint: {
    fontSize: 11,
    color: '#aaa',
    textAlign: 'center',
    marginBottom: 12,
  },
  certLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#EFF6FF',
    padding: 12,
    borderRadius: 10,
    marginBottom: 12,
  },
  certLinkText: {flex: 1, fontSize: 14, color: '#007AFF', fontWeight: '600'},
  noCertBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFF8E1',
    padding: 12,
    borderRadius: 10,
    marginBottom: 12,
  },
  noCertText: {fontSize: 13, color: '#FF9500', fontWeight: '500'},
  actions: {flexDirection: 'row', gap: 10, marginTop: 4},
  editBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#007AFF',
    padding: 11,
    borderRadius: 10,
  },
  banBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#FF3B30',
    padding: 11,
    borderRadius: 10,
  },
  restoreBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#34C759',
    padding: 11,
    borderRadius: 10,
  },
  approveBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#34C759',
    padding: 11,
    borderRadius: 10,
  },
  rejectBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#FF3B30',
    padding: 11,
    borderRadius: 10,
  },
  btnText: {color: '#fff', fontWeight: '700', fontSize: 14},
  actionHint: {fontSize: 12, color: '#888', marginTop: 8},
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  modalTitle: {fontSize: 18, fontWeight: '700', color: '#333'},
  modalScroll: {marginBottom: 16},
  modalLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#666',
    marginBottom: 6,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#E2E2E2',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#333',
    backgroundColor: '#FAFAFA',
    marginBottom: 12,
  },
  modalTextArea: {minHeight: 96},
  modalInputRow: {flexDirection: 'row', gap: 10},
  modalInputColumn: {flex: 1},
  optionRow: {flexDirection: 'row', gap: 8, marginBottom: 12},
  optionChip: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E2E2',
    backgroundColor: '#F6F6F6',
  },
  optionChipActive: {
    backgroundColor: '#FF6B35',
    borderColor: '#FF6B35',
  },
  optionChipText: {fontSize: 13, fontWeight: '600', color: '#666'},
  optionChipTextActive: {color: '#fff'},
  modalActions: {flexDirection: 'row', gap: 10},
  modalCancelButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 10,
    backgroundColor: '#F0F0F0',
  },
  modalCancelButtonText: {fontSize: 14, fontWeight: '600', color: '#666'},
  modalSaveButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 10,
    backgroundColor: '#FF6B35',
  },
  modalSaveButtonText: {fontSize: 14, fontWeight: '700', color: '#fff'},
  emptyContainer: {alignItems: 'center', marginTop: 60, gap: 10},
  empty: {textAlign: 'center', color: '#aaa', fontSize: 15, marginTop: 60},
});
