import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#fff', padding: 20},
  progress: {fontSize: 14, color: '#999', marginBottom: 10},
  question: {fontSize: 22, fontWeight: 'bold', marginBottom: 30, color: '#333'},
  options: {flex: 1},
  option: {padding: 15, borderWidth: 1, borderColor: '#ddd', borderRadius: 8, marginBottom: 10, backgroundColor: '#fff'},
  profileGoalOption: {borderColor: '#FF6B35', borderWidth: 2, backgroundColor: '#FFF0EB'},
  profileGoalRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  profileBadge: {backgroundColor: '#FF6B35', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10},
  profileBadgeSelected: {backgroundColor: 'rgba(255,255,255,0.3)'},
  profileBadgeText: {fontSize: 11, color: '#fff', fontWeight: '700'},
  optionSelected: {backgroundColor: '#FF6B35', borderColor: '#FF6B35'},
  optionText: {fontSize: 16, color: '#333'},
  optionTextSelected: {color: '#fff', fontWeight: '600'},
  input: {borderWidth: 1, borderColor: '#ddd', borderRadius: 8, padding: 15, fontSize: 16, marginTop: 10, color: '#333'},
  navigation: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 20},
  navButton: {padding: 15, borderRadius: 8, backgroundColor: '#FF6B35', flex: 1, marginHorizontal: 5},
  navButtonDisabled: {backgroundColor: '#f0f0f0'},
  navText: {textAlign: 'center', fontSize: 16, fontWeight: '600', color: '#fff'},
  navTextDisabled: {color: '#999'},
  submitButton: {padding: 15, borderRadius: 8, backgroundColor: '#FF6B35', flex: 1, marginHorizontal: 5},
  submitText: {textAlign: 'center', fontSize: 16, fontWeight: '600', color: '#fff'},
  queueOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'center', padding: 24},
  queueCard: {backgroundColor: '#fff', borderRadius: 18, padding: 24, alignItems: 'center'},
  queueTitle: {fontSize: 20, fontWeight: '700', color: '#333', textAlign: 'center', marginTop: 16},
  queueText: {fontSize: 15, color: '#444', textAlign: 'center', lineHeight: 22, marginTop: 12},
  queueSubtext: {fontSize: 13, color: '#888', textAlign: 'center', marginTop: 12},
});
