import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#fff'},
  header: {padding: 20, paddingBottom: 10},
  name: {fontSize: 26, fontWeight: 'bold', color: '#333', marginBottom: 10},
  badges: {flexDirection: 'row', gap: 8, flexWrap: 'wrap'},
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    backgroundColor: '#FFF0EB',
    borderWidth: 1,
    borderColor: '#FF6B35',
  },
  badgeText: {fontSize: 13, fontWeight: '600', color: '#FF6B35'},
  infoRow: {flexDirection: 'row', marginHorizontal: 20, marginVertical: 10, gap: 10},
  infoItem: {
    flex: 1,
    backgroundColor: '#F9F9F9',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    gap: 4,
  },
  infoLabel: {fontSize: 11, color: '#999', marginTop: 4},
  infoValue: {fontSize: 13, fontWeight: '600', color: '#333', textAlign: 'center'},
  section: {marginHorizontal: 20, marginTop: 16},
  sectionTitle: {fontSize: 17, fontWeight: '700', color: '#333', marginBottom: 8},
  videoContainer: {
    height: 200,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#000',
    position: 'relative',
  },
  thumbnail: {width: '100%', height: '100%', resizeMode: 'cover'},
  playOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  video: {flex: 1},
  body: {fontSize: 15, color: '#444', lineHeight: 24},
  stepRow: {flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8},
  stepNumber: {fontSize: 15, fontWeight: '700', color: '#333', marginRight: 8, lineHeight: 24},
  stepText: {flex: 1, fontSize: 15, color: '#444', lineHeight: 24},
  safetyHeader: {flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8},
  ytButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#fff5f5',
    alignSelf: 'flex-start',
  },
  ytButtonText: {fontSize: 13, color: '#FF0000', fontWeight: '600'},
});
