import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F9F9F9'},
  center: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  list: {padding: 16, paddingBottom: 40},
  empty: {alignItems: 'center', paddingTop: 80},
  emptyText: {fontSize: 15, color: '#999', marginTop: 12},
  card: {backgroundColor: '#fff', borderRadius: 14, padding: 14, marginBottom: 12, elevation: 2, shadowColor: '#000', shadowOffset: {width: 0, height: 1}, shadowOpacity: 0.07, shadowRadius: 4},
  cardHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8},
  reasonBadge: {backgroundColor: '#FFF3E0', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8},
  reasonText: {fontSize: 12, fontWeight: '700', color: '#FF9500'},
  dateText: {fontSize: 12, color: '#aaa'},
  postTitle: {fontSize: 15, fontWeight: '700', color: '#1a1a1a', marginBottom: 6},
  row: {flexDirection: 'row', alignItems: 'center', marginBottom: 3},
  meta: {fontSize: 13, color: '#666'},
  description: {fontSize: 13, color: '#555', fontStyle: 'italic', marginTop: 8, padding: 10, backgroundColor: '#F9F9F9', borderRadius: 8},
  actions: {marginTop: 12, flexDirection: 'row', justifyContent: 'flex-end'},
  resolveBtn: {flexDirection: 'row', alignItems: 'center', backgroundColor: '#34C759', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8},
  rejectBtn: {flexDirection: 'row', alignItems: 'center', backgroundColor: '#FF3B30', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8},
  btnText: {color: '#fff', fontWeight: '700', fontSize: 13},
  modalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end'},
  modalBox: {backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, paddingBottom: 40},
  modalTitle: {fontSize: 18, fontWeight: '700', color: '#333', marginBottom: 6},
  modalSub: {fontSize: 13, color: '#888', marginBottom: 4},
  noteInput: {borderWidth: 1, borderColor: '#E0E0E0', borderRadius: 10, padding: 12, fontSize: 14, color: '#333', marginTop: 12, marginBottom: 16, minHeight: 80},
  modalBtns: {flexDirection: 'row', gap: 8},
  cancelBtn: {flex: 1, padding: 14, borderRadius: 12, alignItems: 'center', backgroundColor: '#F0F0F0'},
  cancelText: {color: '#666', fontWeight: '600'},
});
