import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#fff'},
  image: {width: '100%', height: 240, resizeMode: 'cover'},
  imagePlaceholder: {width: '100%', height: 240, backgroundColor: '#F0F0F0', justifyContent: 'center', alignItems: 'center'},
  content: {padding: 20},
  title: {fontSize: 24, fontWeight: 'bold', color: '#333', marginBottom: 12},
  metaRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20, alignItems: 'center'},
  metaItem: {flexDirection: 'row', alignItems: 'center', gap: 4},
  metaText: {fontSize: 14, color: '#888'},
  cuisineBadge: {flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, backgroundColor: '#FFF1EB', borderWidth: 1, borderColor: '#FF6B35'},
  cuisineText: {fontSize: 12, color: '#FF6B35', fontWeight: '600'},
  badge: {paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, borderWidth: 1},
  badgeText: {fontSize: 12, fontWeight: '600'},
  macroGrid: {flexDirection: 'row', gap: 10, marginBottom: 24},
  macroBox: {flex: 1, backgroundColor: '#F9F9F9', borderRadius: 12, padding: 12, alignItems: 'center', gap: 2},
  macroValue: {fontSize: 18, fontWeight: 'bold', marginTop: 4},
  macroUnit: {fontSize: 11, color: '#999'},
  macroLabel: {fontSize: 11, color: '#666', fontWeight: '500'},
  section: {marginBottom: 24},
  sectionTitle: {fontSize: 18, fontWeight: '700', color: '#333', marginBottom: 12},
  ingredientRow: {flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#F0F0F0', gap: 10},
  bullet: {width: 7, height: 7, borderRadius: 4, backgroundColor: '#34C759'},
  ingredientText: {fontSize: 15, color: '#444', flex: 1},
  ingredientAmount: {fontSize: 13, color: '#888', fontWeight: '500'},
  stepRow: {flexDirection: 'row', gap: 10, marginBottom: 12, alignItems: 'flex-start'},
  stepNumber: {fontSize: 15, fontWeight: '700', color: '#34C759', minWidth: 24},
  stepText: {flex: 1, fontSize: 15, color: '#444', lineHeight: 22},
  noInstructions: {fontSize: 14, color: '#aaa', fontStyle: 'italic'},
  tagsRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  tag: {paddingHorizontal: 12, paddingVertical: 5, borderRadius: 16, backgroundColor: '#F0FFF4', borderWidth: 1, borderColor: '#34C759'},
  tagText: {fontSize: 12, color: '#34C759', fontWeight: '600', textTransform: 'capitalize'},
});
