import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F5F5F5'},
  planHeroSection: {backgroundColor: '#fff', padding: 20, marginTop: 10},
  planHeroSubtitle: {
    fontSize: 13,
    color: '#666',
    lineHeight: 20,
    marginTop: -6,
    marginBottom: 16,
  },
  planCardsColumn: {gap: 12},
  planCard: {
    backgroundColor: '#FAFAFA',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  planCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  planIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  planStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  planStatusBadgeText: {fontSize: 11, fontWeight: '700'},
  planCardTitle: {fontSize: 16, fontWeight: '700', color: '#333'},
  planCardDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 20,
    marginTop: 8,
  },
  planCardFooter: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  planCardActionText: {fontSize: 13, fontWeight: '700'},
  healthSection: {backgroundColor: '#fff', padding: 20, marginTop: 10},
  healthRow: {flexDirection: 'row', justifyContent: 'space-between'},
  healthBox: {alignItems: 'center'},
  healthValue: {fontSize: 16, fontWeight: 'bold', color: '#333', marginTop: 4},
  healthLabel: {fontSize: 11, color: '#666', marginTop: 2},
  section: {backgroundColor: '#fff', padding: 20, marginTop: 10},
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  statsContainer: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  statCard: {
    flex: 1,
    minWidth: '47%',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statValue: {fontSize: 20, fontWeight: 'bold', color: '#fff', marginTop: 8},
  statLabel: {fontSize: 11, color: '#fff', marginTop: 4, textAlign: 'center'},
  scheduleItem: {
    flexDirection: 'row',
    backgroundColor: '#F9F9F9',
    padding: 15,
    paddingLeft: 18,
    borderRadius: 12,
    marginBottom: 10,
  },
  scheduleTime: {flexDirection: 'row', alignItems: 'center', marginRight: 15},
  scheduleTimeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FF6B35',
    marginLeft: 5,
  },
  scheduleInfo: {flex: 1},
  scheduleClient: {fontSize: 15, fontWeight: '600', color: '#333'},
  scheduleType: {fontSize: 13, color: '#666', marginTop: 2},
  scheduleExerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingLeft: 12,
  },
  scheduleExerciseRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  scheduleCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#ccc',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  scheduleCheckboxDone: {borderColor: '#34C759', backgroundColor: '#34C759'},
  scheduleExerciseName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  scheduleExerciseNameDone: {textDecorationLine: 'line-through', color: '#999'},
  scheduleExerciseDetail: {fontSize: 12, color: '#666'},
  syncReminder: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    backgroundColor: '#E3F2FD',
    padding: 10,
    borderRadius: 10,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  syncReminderText: {flex: 1, fontSize: 12, color: '#1565C0', lineHeight: 18},
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  activityIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  activityInfo: {flex: 1, marginLeft: 12},
  activityClient: {fontSize: 14, fontWeight: '600', color: '#333'},
  activityText: {fontSize: 13, color: '#666', marginTop: 2},
  activityTime: {fontSize: 11, color: '#999', marginTop: 2},
  topClientsContainer: {flexDirection: 'row', gap: 10},
  topClientCard: {
    flex: 1,
    backgroundColor: '#F9F9F9',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  topClientRank: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#FFD700',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rankText: {fontSize: 11, fontWeight: 'bold', color: '#fff'},
  topClientAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FF6B35',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  avatarText: {fontSize: 16, fontWeight: 'bold', color: '#fff'},
  topClientName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
  },
  streakBadge: {
    backgroundColor: '#FFF0EB',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 6,
  },
  streakText: {fontSize: 11, color: '#FF6B35', fontWeight: '600'},
  actionsGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  actionCard: {
    flex: 1,
    minWidth: '47%',
    height: 100,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  actionText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  map: {width: '100%', height: 220, borderRadius: 12},
  mapPlaceholder: {
    width: '100%',
    height: 220,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {marginTop: 8, fontSize: 13, color: '#666'},
  findGymsButton: {
    marginTop: 10,
    backgroundColor: '#FF6B35',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  findGymsButtonText: {color: '#fff', fontWeight: '600', fontSize: 14},
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  seeAllText: {fontSize: 14, color: '#FF6B35', fontWeight: '600'},
  browseCard: {
    backgroundColor: '#F9F9F9',
    borderRadius: 12,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  browseCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  browseCardText: {flex: 1},
  browseCardTitle: {fontSize: 15, fontWeight: '600', color: '#333'},
  browseCardSub: {fontSize: 12, color: '#888', marginTop: 2},
  pendingBanner: {
    backgroundColor: '#FFF8E1',
    borderLeftWidth: 4,
    borderLeftColor: '#FF9500',
    margin: 12,
    borderRadius: 10,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  pendingBannerText: {flex: 1},
  pendingBannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333',
    marginBottom: 3,
  },
  pendingBannerSub: {fontSize: 12, color: '#666', lineHeight: 18},
  challengeCard: {
    backgroundColor: '#FAFAFA',
    borderRadius: 16,
    padding: 15,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  challengeTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  challengeBadgeRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, flex: 1},
  challengeTypeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: 'flex-start',
  },
  challengeTypeChipAuto: {backgroundColor: '#EAF3FF'},
  challengeTypeChipManual: {backgroundColor: '#F3ECFF'},
  challengeTypeText: {fontSize: 11, fontWeight: '700'},
  challengeTypeTextAuto: {color: '#007AFF'},
  challengeTypeTextManual: {color: '#7C3AED'},
  challengeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  challengeName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#333',
    flex: 1,
    marginRight: 8,
  },
  challengeDaysPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: '#FFF0EB',
  },
  challengeDays: {fontSize: 12, color: '#FF6B35', fontWeight: '700'},
  challengeProgressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  challengeMetricText: {fontSize: 12, fontWeight: '600', color: '#444'},
  challengePercentStrong: {fontSize: 12, fontWeight: '700', color: '#FF6B35'},
  challengeProgress: {
    height: 8,
    backgroundColor: '#E0E0E0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  challengeProgressFill: {height: '100%', backgroundColor: '#FF6B35'},
  challengePercent: {fontSize: 12, color: '#666', marginTop: 6, lineHeight: 18},
  challengeMetaRow: {flexDirection: 'row', alignItems: 'center', marginTop: 6},
  challengeMetaText: {fontSize: 12, color: '#666', marginLeft: 6},
  challengeFooter: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  challengeFooterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFEFEF',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 14,
  },
  challengeFooterText: {fontSize: 12, fontWeight: '600', color: '#555'},
  challengeNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
  },
  challengeNoticeReady: {backgroundColor: '#E9F8EE'},
  challengeNoticePending: {backgroundColor: '#FFF4DD'},
  challengeNoticeScheduled: {backgroundColor: '#E8F2FF'},
  challengeNoticeText: {flex: 1, fontSize: 12, fontWeight: '600'},
  challengeNoticeTextReady: {color: '#1B8A3C'},
  challengeNoticeTextPending: {color: '#B26A00'},
  challengeNoticeTextScheduled: {color: '#1565C0'},
  challengeEmptyCard: {
    backgroundColor: '#F9F9F9',
    borderRadius: 12,
    padding: 15,
  },
  challengeEmptyText: {fontSize: 15, fontWeight: '600', color: '#333'},
  challengeEmptySubText: {fontSize: 13, color: '#999', marginTop: 4},
});
