import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F9F9F9'},
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
  },
  emptyTitle: {fontSize: 18, color: '#333', marginTop: 15, fontWeight: '600'},
  emptySubtitle: {color: '#999', marginTop: 8, textAlign: 'center'},
  emptyButton: {
    marginTop: 20,
    backgroundColor: '#FF6B35',
    padding: 14,
    borderRadius: 12,
  },
  emptyButtonText: {color: '#fff', fontWeight: '600'},
  statusBanner: {padding: 20, margin: 15, borderRadius: 16},
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  statusTitle: {fontSize: 16, fontWeight: 'bold'},
  adminNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.08)',
  },
  adminNoteText: {fontSize: 13, flex: 1, fontStyle: 'italic'},
  planHeader: {backgroundColor: '#fff', padding: 20, marginBottom: 10},
  aiTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#FFF0EB',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 12,
  },
  aiTagText: {fontSize: 12, fontWeight: '600', color: '#FF6B35'},
  planName: {fontSize: 22, fontWeight: 'bold', color: '#333', marginBottom: 4},
  generatedAt: {fontSize: 13, color: '#999'},
  section: {backgroundColor: '#fff', padding: 20, marginBottom: 10},
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  dayCard: {
    backgroundColor: '#F9F9F9',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
  },
  dayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  dayBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FF6B35',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayBadgeToday: {backgroundColor: '#34C759'},
  dayBadgeText: {fontSize: 14, fontWeight: 'bold', color: '#fff'},
  dayName: {fontSize: 16, fontWeight: '600', color: '#333', flex: 1},
  doneCount: {fontSize: 12, color: '#999'},
  exerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  exerciseRowFaded: {opacity: 0.5},
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#ccc',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  checkboxDone: {borderColor: '#34C759', backgroundColor: '#34C759'},
  checkboxLocked: {borderColor: '#eee', backgroundColor: '#f5f5f5'},
  exerciseInfo: {flex: 1},
  exerciseName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  exerciseNameDone: {textDecorationLine: 'line-through', color: '#999'},
  exerciseDetail: {fontSize: 12, color: '#666'},
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    backgroundColor: '#FF6B35',
    padding: 14,
    borderRadius: 12,
  },
  primaryButtonText: {fontSize: 14, fontWeight: '700', color: '#fff'},
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    borderWidth: 1.5,
    borderColor: '#FF6B35',
    padding: 14,
    borderRadius: 12,
  },
  secondaryButtonDisabled: {opacity: 0.6},
  secondaryButtonText: {fontSize: 14, fontWeight: '700', color: '#FF6B35'},
  regenerateHint: {fontSize: 12, color: '#888', marginTop: 8, lineHeight: 18},
  queueBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFF7E6',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    marginTop: 12,
  },
  queueBannerText: {fontSize: 12, color: '#B26A00', fontWeight: '600'},
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    gap: 14,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {fontSize: 18, fontWeight: '700', color: '#333'},
  modalDescription: {fontSize: 13, color: '#666', lineHeight: 20},
  modalSectionTitle: {fontSize: 13, fontWeight: '700', color: '#333'},
  reasonChips: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  reasonChip: {
    backgroundColor: '#F3F4F6',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  reasonChipActive: {backgroundColor: '#FF6B35'},
  reasonChipText: {fontSize: 12, fontWeight: '600', color: '#555'},
  reasonChipTextActive: {color: '#fff'},
  feedbackInput: {
    minHeight: 96,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#333',
    backgroundColor: '#FAFAFA',
  },
  modalActions: {flexDirection: 'row', gap: 10},
  modalCancelButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
  },
  modalCancelButtonText: {fontSize: 14, fontWeight: '600', color: '#666'},
  modalSubmitButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#FF6B35',
  },
  modalSubmitButtonText: {fontSize: 14, fontWeight: '700', color: '#fff'},
});
