import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#f5f5f5'},
  loadingContainer: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  header: {backgroundColor: '#fff', padding: 20, borderBottomWidth: 1, borderBottomColor: '#eee'},
  title: {fontSize: 28, fontWeight: 'bold', marginBottom: 4},
  subtitle: {fontSize: 14, color: '#666'},
  searchContainer: {flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', padding: 12, marginHorizontal: 16, marginTop: 12, borderRadius: 8, gap: 8},
  searchInput: {flex: 1, fontSize: 16},
  filterContainer: {flexDirection: 'row', padding: 16, gap: 8},
  filterButton: {flex: 1, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, backgroundColor: '#f0f0f0', alignItems: 'center'},
  filterButtonActive: {backgroundColor: '#007AFF'},
  filterText: {fontSize: 14, fontWeight: '600', color: '#666'},
  filterTextActive: {color: '#fff'},
  listContainer: {padding: 16},
  contentCard: {backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 12, elevation: 2, shadowColor: '#000', shadowOffset: {width: 0, height: 2}, shadowOpacity: 0.1, shadowRadius: 4},
  contentHeader: {flexDirection: 'row', marginBottom: 12},
  typeIcon: {width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginRight: 12},
  contentInfo: {flex: 1},
  contentTitle: {fontSize: 16, fontWeight: '600', marginBottom: 4},
  contentDescription: {fontSize: 14, color: '#666', lineHeight: 20},
  contentMeta: {flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#f0f0f0'},
  metaItem: {flexDirection: 'row', alignItems: 'center', gap: 4},
  metaText: {fontSize: 12, color: '#666'},
  statusBadge: {paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, marginLeft: 'auto'},
  statusText: {fontSize: 10, fontWeight: '600', color: '#fff'},
  actionButtons: {flexDirection: 'row', gap: 8},
  actionButton: {flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 10, borderRadius: 8, gap: 4},
  editButton: {backgroundColor: '#E3F2FD'},
  editButtonText: {fontSize: 14, fontWeight: '600', color: '#007AFF'},
  deleteButton: {backgroundColor: '#FFEBEE'},
  deleteButtonText: {fontSize: 14, fontWeight: '600', color: '#FF3B30'},
  emptyContainer: {alignItems: 'center', justifyContent: 'center', paddingVertical: 60},
  emptyText: {fontSize: 16, color: '#999', marginTop: 16, marginBottom: 24},
  createButton: {flexDirection: 'row', alignItems: 'center', backgroundColor: '#007AFF', paddingHorizontal: 20, paddingVertical: 12, borderRadius: 8, gap: 6},
  createButtonText: {color: '#fff', fontSize: 16, fontWeight: '600'},
  fab: {position: 'absolute', bottom: 20, right: 20, width: 56, height: 56, borderRadius: 28, backgroundColor: '#007AFF', justifyContent: 'center', alignItems: 'center', elevation: 4, shadowColor: '#000', shadowOffset: {width: 0, height: 2}, shadowOpacity: 0.3, shadowRadius: 4},
});
