import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#f5f5f5'},
  center: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  tab: {flex: 1, paddingVertical: 14, alignItems: 'center'},
  tabActive: {borderBottomWidth: 2, borderBottomColor: '#FF6B35'},
  tabText: {fontSize: 14, fontWeight: '600', color: '#999'},
  tabTextActive: {color: '#FF6B35'},
  empty: {alignItems: 'center', paddingTop: 80},
  emptyText: {fontSize: 15, color: '#999', marginTop: 12},
  card: {
    backgroundColor: '#fff',
    marginHorizontal: 12,
    marginTop: 10,
    borderRadius: 12,
    padding: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  cardHeader: {flexDirection: 'row', alignItems: 'center', marginBottom: 10},
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FF6B35',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {fontSize: 18, fontWeight: 'bold', color: '#fff'},
  info: {flex: 1},
  name: {fontSize: 15, fontWeight: '700', color: '#1a1a1a'},
  sub: {fontSize: 13, color: '#666', marginTop: 2},
  price: {fontSize: 13, color: '#34C759', fontWeight: '600', marginTop: 2},
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  contactText: {fontSize: 12, color: '#666'},
  profileFactsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  profileFactChip: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  profileFactText: {fontSize: 11, color: '#555', fontWeight: '600'},
  dateRow: {flexDirection: 'row', alignItems: 'center', marginTop: 4},
  dateText: {fontSize: 12, color: '#888', marginTop: 4},
  noticeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  noticeText: {fontSize: 12, fontWeight: '500'},
  acceptBtn: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#34C759',
    padding: 10,
    borderRadius: 8,
  },
  declineBtn: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FF3B30',
    padding: 10,
    borderRadius: 8,
  },
  chatBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#007AFF',
    padding: 10,
    borderRadius: 8,
    marginTop: 4,
  },
  btnText: {color: '#fff', fontWeight: '600', fontSize: 14},
  actions: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4},
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
    marginTop: 16,
    marginBottom: 2,
  },
  postHeaderText: {fontSize: 13, fontWeight: '700', color: '#FF6B35'},
});
