import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F5F5F5'},
  header: {
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  searchRow: {flexDirection: 'row', alignItems: 'center', gap: 10},
  searchInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    paddingHorizontal: 12,
    minHeight: 46,
  },
  searchIcon: {marginRight: 8},
  searchInput: {flex: 1, fontSize: 15, color: '#333', paddingVertical: 10},
  filterButton: {
    width: 46,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#FFF1EB',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  filterCountBadge: {
    position: 'absolute',
    top: 6,
    right: 5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FF6B35',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  filterCountText: {fontSize: 11, fontWeight: '700', color: '#fff'},
  activeFilterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    gap: 10,
  },
  activeFilterScroll: {gap: 8, paddingRight: 8},
  activeFilterChip: {
    backgroundColor: '#FFF1EB',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  activeFilterChipText: {fontSize: 12, fontWeight: '600', color: '#FF6B35'},
  clearFiltersText: {fontSize: 13, fontWeight: '700', color: '#FF6B35'},
  filterSection: {marginBottom: 18},
  filterLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333',
    marginBottom: 10,
  },
  optionRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  optionChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#F3F4F6',
  },
  optionChipActive: {backgroundColor: '#FF6B35'},
  optionChipText: {fontSize: 13, fontWeight: '600', color: '#555'},
  optionChipTextActive: {color: '#fff'},
  list: {padding: 12, gap: 10},
  listContainer: {flex: 1},
  card: {backgroundColor: '#fff', borderRadius: 12, padding: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', elevation: 1, shadowColor: '#000', shadowOffset: {width: 0, height: 1}, shadowOpacity: 0.06, shadowRadius: 2},
  cardLeft: {flex: 1},
  cardName: {fontSize: 16, fontWeight: '600', color: '#333'},
  cardSub: {fontSize: 13, color: '#888', marginTop: 3},
  cardRight: {alignItems: 'flex-end'},
  diffBadge: {paddingHorizontal: 10, paddingVertical: 3, borderRadius: 10},
  diffText: {fontSize: 12, fontWeight: '600'},
  empty: {alignItems: 'center', marginTop: 60, gap: 10},
  emptyText: {fontSize: 15, color: '#aaa'},
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
    maxHeight: '82%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  modalTitle: {fontSize: 20, fontWeight: '700', color: '#111'},
  modalContent: {paddingBottom: 12},
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  resetButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    paddingVertical: 14,
    alignItems: 'center',
  },
  resetButtonText: {fontSize: 14, fontWeight: '700', color: '#555'},
  applyButton: {
    flex: 1.2,
    borderRadius: 12,
    backgroundColor: '#FF6B35',
    paddingVertical: 14,
    alignItems: 'center',
  },
  applyButtonText: {fontSize: 14, fontWeight: '700', color: '#fff'},
});
