import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F9F9F9'},
  center: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  statsBar: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  statItem: {flex: 1, alignItems: 'center'},
  statValue: {fontSize: 20, fontWeight: '700', color: '#FF6B35'},
  statValueGreen: {fontSize: 20, fontWeight: '700', color: '#34C759'},
  statValueRed: {fontSize: 20, fontWeight: '700', color: '#FF3B30'},
  statValueOrange: {fontSize: 20, fontWeight: '700', color: '#FF9500'},
  statLabel: {fontSize: 11, color: '#888', marginTop: 2},
  codeBanner: {backgroundColor: '#FF6B35', padding: 20, alignItems: 'center'},
  codeBannerLabel: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.8)',
    marginBottom: 8,
  },
  codeText: {fontSize: 42, fontWeight: '900', color: '#fff', letterSpacing: 8},
  codeExpiry: {fontSize: 12, color: 'rgba(255,255,255,0.7)', marginTop: 6},
  codeDismiss: {marginTop: 10},
  codeDismissText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    textDecorationLine: 'underline',
  },
  list: {padding: 16, paddingBottom: 40},
  empty: {textAlign: 'center', color: '#999', marginTop: 40},
  historyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  historyBannerText: {fontSize: 13, fontWeight: '600', color: '#555'},
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  cardLeft: {flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1},
  cardInfo: {flex: 1},
  cardDay: {fontSize: 14, fontWeight: '600', color: '#1a1a1a'},
  cardTime: {fontSize: 13, fontWeight: '500', color: '#444', marginTop: 2},
  cardDate: {fontSize: 12, color: '#888', marginTop: 2},
  notePreview: {fontSize: 12, color: '#FF6B35', marginTop: 4, lineHeight: 16},
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  noteBtn: {padding: 6},
  planBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EAF3FF',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
  },
  planBtnText: {color: '#007AFF', fontWeight: '700', fontSize: 12},
  startBtn: {
    backgroundColor: '#FF6B35',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  startBtnText: {color: '#fff', fontWeight: '700', fontSize: 13},
  waitingBadge: {
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  waitingText: {color: '#007AFF', fontSize: 12, fontWeight: '600'},
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalBox: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: {fontSize: 18, fontWeight: '700', color: '#333', marginBottom: 6},
  modalSubtitle: {fontSize: 13, color: '#888', marginBottom: 12},
  noteInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#333',
    minHeight: 130,
    textAlignVertical: 'top',
    marginBottom: 16,
  },
  modalBtns: {flexDirection: 'row', gap: 10},
  cancelBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#F0F0F0',
  },
  cancelText: {color: '#666', fontWeight: '600'},
  saveBtn: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#FF6B35',
  },
  saveText: {color: '#fff', fontWeight: '700'},
});
