import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F5F5F5', padding: 16},
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#555',
    marginBottom: 6,
    marginTop: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  hint: {fontSize: 12, color: '#999', fontWeight: '400', textTransform: 'none'},
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    color: '#333',
  },
  textArea: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    color: '#333',
    height: 90,
    textAlignVertical: 'top',
  },
  optionRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  optionBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  optionBtnActive: {backgroundColor: '#FF6B35', borderColor: '#FF6B35'},
  optionText: {fontSize: 13, color: '#666', fontWeight: '500'},
  optionTextActive: {color: '#fff', fontWeight: '600'},
  dateModeHint: {fontSize: 12, color: '#777', marginTop: -8, marginBottom: 8},
  button: {
    backgroundColor: '#FF6B35',
    padding: 15,
    borderRadius: 12,
    marginTop: 24,
    alignItems: 'center',
  },
  buttonInner: {flexDirection: 'row', alignItems: 'center', gap: 8},
  buttonText: {color: '#fff', fontSize: 16, fontWeight: '700'},
  bottomSpacer: {height: 40},
});
