import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F9F9F9', padding: 20},
  title: {fontSize: 28, fontWeight: 'bold', marginBottom: 30, color: '#333'},
  sectionTitle: {fontSize: 20, fontWeight: 'bold', marginTop: 20, marginBottom: 15, color: '#FF6B35'},
  label: {fontSize: 14, fontWeight: '600', marginBottom: 8, color: '#333'},
  input: {borderWidth: 1, borderColor: '#E0E0E0', padding: 12, borderRadius: 8, marginBottom: 20, fontSize: 16, backgroundColor: '#fff'},
  inputError: {borderColor: '#FF3B30', marginBottom: 6},
  fieldError: {fontSize: 12, color: '#FF3B30', marginTop: -2, marginBottom: 12, marginLeft: 2},
  dateInput: {justifyContent: 'center'},
  button: {backgroundColor: '#FF6B35', padding: 15, borderRadius: 8, marginTop: 10, marginBottom: 30},
  buttonText: {color: '#fff', textAlign: 'center', fontSize: 16, fontWeight: '600'},
  switchRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff', padding: 16, borderRadius: 12, marginBottom: 12, borderWidth: 1, borderColor: '#E0E0E0'},
  switchTextContainer: {flex: 1, marginRight: 12},
  switchLabel: {fontSize: 16, fontWeight: '600', color: '#333', marginBottom: 4},
  switchDescription: {fontSize: 13, color: '#666'},
  // Date picker modal
  modalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center'},
  modalBox: {backgroundColor: '#fff', borderRadius: 20, padding: 20, width: '85%', maxHeight: '70%'},
  modalTitle: {fontSize: 20, fontWeight: 'bold', color: '#333', marginBottom: 20, textAlign: 'center'},
  modalColumns: {flexDirection: 'row', gap: 10, marginBottom: 20},
  modalCol: {flex: 1},
  modalColLabel: {fontSize: 14, fontWeight: '600', color: '#FF6B35', textAlign: 'center', marginBottom: 10},
  modalPicker: {height: 200, borderWidth: 1, borderColor: '#E0E0E0', borderRadius: 10},
  modalItem: {padding: 12, alignItems: 'center'},
  modalItemActive: {backgroundColor: '#FF6B35'},
  modalItemText: {fontSize: 16, color: '#333'},
  modalItemTextActive: {color: '#fff', fontWeight: 'bold'},
  modalButtons: {flexDirection: 'row', gap: 10},
  modalCancelBtn: {flex: 1, padding: 14, borderRadius: 12, alignItems: 'center', backgroundColor: '#F0F0F0'},
  modalConfirmBtn: {flex: 1, padding: 14, borderRadius: 12, alignItems: 'center', backgroundColor: '#FF6B35'},
  modalCancelText: {color: '#666', fontSize: 16, fontWeight: '600'},
  modalConfirmText: {color: '#fff', fontSize: 16, fontWeight: 'bold'},
});
