import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#f5f5f5'},
  content: {padding: 16, paddingBottom: 32},
  sectionLabel: {fontSize: 18, fontWeight: '700', color: '#111', marginTop: 8, marginBottom: 12},
  empty: {fontSize: 14, color: '#999', marginBottom: 16},
  card: {backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 14, elevation: 2, shadowColor: '#000', shadowOffset: {width: 0, height: 2}, shadowOpacity: 0.08, shadowRadius: 4},
  cardHeader: {flexDirection: 'row', alignItems: 'center', marginBottom: 10},
  avatar: {width: 48, height: 48, borderRadius: 24, marginRight: 12},
  avatarPlaceholder: {width: 48, height: 48, borderRadius: 24, backgroundColor: '#007AFF', justifyContent: 'center', alignItems: 'center', marginRight: 12},
  avatarText: {fontSize: 20, fontWeight: 'bold', color: '#fff'},
  headerInfo: {flex: 1},
  trainerName: {fontSize: 16, fontWeight: '600', color: '#111', marginBottom: 4},
  statusBadge: {alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10},
  statusActive: {backgroundColor: '#E8F5E9'},
  statusExpired: {backgroundColor: '#FFEBEE'},
  statusText: {fontSize: 11, fontWeight: '600', color: '#333'},
  price: {fontSize: 16, fontWeight: 'bold', color: '#34C759'},
  priceSuffix: {fontSize: 12, fontWeight: '400', color: '#666'},
  specializationRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10},
  badge: {backgroundColor: '#E3F2FD', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12},
  badgeText: {fontSize: 11, color: '#007AFF', fontWeight: '500'},
  contactRow: {flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 8, marginBottom: 8},
  dateRow: {flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 12},
  dateText: {fontSize: 13, color: '#666'},
  actions: {flexDirection: 'row', flexWrap: 'wrap', gap: 10, alignItems: 'center', marginTop: 10},
  rateButton: {flexDirection: 'row', alignItems: 'center', backgroundColor: '#FF9500', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, gap: 6},
  rateButtonText: {color: '#fff', fontSize: 13, fontWeight: '600'},
  renewButton: {flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: '#007AFF', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, gap: 6},
  renewButtonText: {color: '#007AFF', fontSize: 13, fontWeight: '600'},
  activeInfo: {flexDirection: 'row', alignItems: 'flex-start', gap: 6},
  activeInfoText: {
    flex: 1,
    flexShrink: 1,
    fontSize: 13,
    lineHeight: 18,
    color: '#34C759',
    fontWeight: '500',
  },
});
